project/main/urls.py
from django.conf.urls import url, include

from .views import MainpageView, HistoryListView, FaqListView,ChatListView


urlpatterns = [
	url(r'^chat/', ChatListView.as_view(), name='chat'),
    url(r'^history/', HistoryListView.as_view(), name='history'),
    url(r'^faq/', FaqListView.as_view(), name='faq'),
    url(r'^', MainpageView.as_view(), name='mainpage')
]

project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from authentication.views import RegisterFormView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login,
        {'template_name': 'enter.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

project/authentication/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class Faculty(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Факультет'
        verbose_name_plural = 'Факультеты'


class City(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'


class MyUserManager(BaseUserManager):
    def create_user(self, first_name, last_name, date_of_birth, email, gender,
                    faculty, phone_number, city, address, password=None):
        if not email:
            raise ValueError('пользователь должен иметь email')

        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
            gender=gender,
            faculty=faculty,
            phone_number=phone_number,
            city=city,
            address=address
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, password, date_of_birth=None, gender=None,
                         faculty=None, phone_number=None, city=None, address=None):
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            password=password,
            date_of_birth=date_of_birth,
            gender=gender,
            faculty=faculty,
            phone_number=phone_number,
            city=city,
            address=address
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    first_name = models.CharField(verbose_name='имя',
                                  max_length=100)
    last_name = models.CharField(verbose_name='фамилия',
                                 max_length=100)
    date_of_birth = models.DateField(verbose_name='день рождения', blank=True,
                                     default=None, null=True)
    email = models.EmailField(verbose_name='email',
                              max_length=255, unique=True)
    GENDER_CHOICES = (
        ('male', 'мужской'),
        ('female', 'женский'),
    )
    gender = models.CharField(max_length=20, verbose_name='пол',
                              choices=GENDER_CHOICES, blank=True,
                              default=None, null=True)
    faculty = models.ForeignKey(Faculty, verbose_name='факультет',
                                blank=True, default=None, null=True)
    phone_number = models.CharField(max_length=20, verbose_name='номер телефона',
                                    blank=True, default=None, null=True)
    city = models.ForeignKey(City, verbose_name='город',
                             blank=True, default=None, null=True)
    address = models.CharField(max_length=100, verbose_name='адрес',
                               blank=True, default=None, null=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        return self.is_admin

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

project/main/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст статьи')
    image = models.ImageField(upload_to='images', verbose_name='Картинка',
                              blank=True, default=None)
    pub_date = models.DateTimeField(verbose_name='Опубликована', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class History(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст статьи')
    image = models.ImageField(upload_to='images', verbose_name='Картинка',
                              blank=True, default=None)
    pub_date = models.DateTimeField(verbose_name='Опубликована', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Статья | История'
        verbose_name_plural = 'Статьи | История'


class Faq(models.Model):
    question = models.CharField(max_length=255, verbose_name='Вопрос')
    answer = models.TextField(verbose_name='Ответ')

    def __str__(self):
        return self.question

    class Meta:
        ordering = ['-id']
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQ'

project/authentication/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView

from .admin import UserCreationForm


class RegisterFormView(FormView):
    form_class = UserCreationForm
    template_name = "registration.html"
    success_url = "login"

    def form_valid(self, form):
        form.save()

        return super(RegisterFormView, self).form_valid(form)

project/main/views.py
from django.shortcuts import render
from django.views.generic import ListView

from .models import Article, History, Faq


class MainpageView(ListView):
    model = Article
    template_name = 'index.html'
    paginate_by = 10
    allow_empty = True


class HistoryListView(ListView):
    model = History
    template_name = 'history.html'
    paginate_by = 10
    allow_empty = True


class FaqListView(ListView):
    model = Faq
    template_name = 'faq.html'
    allow_empty = True


class ChatListView(ListView):
    template_name = 'chat.html'
    paginate_by = 10
    allow_empty = True

project/templates/.c9/metadata/workspace/hello-world.html
{"filter":false,"title":"hello-world.html","tooltip":"/hello-world.html","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":60,"scrollleft":0,"selection":{"start":{"row":0,"column":0},"end":{"row":0,"column":0},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":4,"state":"start","mode":"ace/mode/html"}},"timestamp":1468316118695,"hash":"71161fd5afd1b1b584bace2b3009d56e60b00e99"}

project/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="Kazakhstan student society in Austria" content="">
    <meta name="Author: Pelykh Ivan" content="">
    <title>Kazakhstan student society in Austria</title>

     {% block additional_css %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/animate.min.css" %}" rel="stylesheet">
    <link href="{% static "css/prettyPhoto.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <link href="{% static "css/responsive.css" %}" rel="stylesheet">
     {% endblock %}
    {% block additional_js %}
        <script src="{% static "js/html5shiv.js" %}"></script>
        <script src="{% static "js/respond.min.js" %}"></script>
    {% endblock %}
    <!--[if lt IE 9]>

    <![endif]-->

</head>

  <body>
  {% block content %}
  {% endblock %}

   <!-- SCRIPTS-->
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery.prettyPhoto.js" %}"></script>
    <script src="{% static "js/jquery.isotope.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
    <script src="{% static "js/wow.min.js" %}"></script>
    <script src="{% static "js/timeline.js" %}"></script>
  </body>
</html>

project/templates/charity.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Kazakhstan student society in Austria</title>
  
  <!-- core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    
</head>

  <body class="homepage">

<nav class="navbar navbar-default" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand" href="index.html"><img src="images/logo-kz.png" alt="logo"></a>
    </div>
<div class="collapse navbar-collapse navbar-right">
    <ul class="nav navbar-nav">
        <li><a href="index.html">Главная</a></li>    
        <li><a href="event.html">События</a></li>
        <li><a href="history.html">История</a></li>
        <li><a href="faq.html">FAQ</a></li>
        <li><a href="charity.html">Благотворительность</a></li>
        <li><a href="partners.html">Партнеры</a></li>

      <li class="dropdown">
        <a href="chat.html" class="dropdown-toggle" data-toggle="dropdown">Чат <i class="fa fa-angle-down"></i></a>
        <ul class="dropdown-menu">
          <li><a href="chat.html">Общий чат</a></li>
        
          <li><a href="#">Чат факультета</a></li>
        </ul>
    </li>
      <li><a href="enter.html">Вход</a></li>
    </ul>
   </div>
  </div> 
</nav>    

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>



<footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2016 <a target="_blank" href="http://vk.com/ivanulo" title="Kazakhstan student society">Our web-stud</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                    <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li> 
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                            </ul>
                        <li><a href="#">Главная</a></li>
                        <li><a href="#">Наша история</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

   <!-- SCRIPTS-->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/jquery.isotope.min.js"></script>
    <script src="js/main.js"></script>
    <script src="js/wow.min.js"></script>
    <script src="js/timeline.js"></script>
  </body>
</html>

project/templates/chat.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block main %}
<!--CHAT START HERE -->
<script type="text/javascript" src="{% static "https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js" %}" ></script>
<script type="text/javascript" src="{%static "https://comet-server.ru/CometServerApi.js"%}" ></script>
<script type="text/javascript" src="{%static "https://comet-server.ru/doc/html_chat.js"%}" ></script>
<link rel="stylesheet" type="text/css" href="{% static "https://comet-server.ru/doc/html_chat.css"%}"></link>
 
<!-- Осталось настроить сам чат и запустить, для этого пишем небольшой скрипт. -->
<div id="html-chat"></div>
<style>
/* Здесь настроим css стили для чата*/
.holder-html-chat{ border: 3px solid #428bca;padding:10px;background-color: #fff; width: 100%;}
.html-chat-history{ min-width: 100%;  overflow: auto; min-height:350px; max-height: 600px; border: 2px solid #428bca; padding: 90px; border-radius: 3%;}
.html-chat-js-name{ border-width: 1px; border-color: #428bca; height: 50px; border-radius: 5%; margin-top:22px;}
.html-chat-js-input{max-width: 600px; max-height: 100px; margin-top:10px; border-radius: 5%; margin-left: 3px; background-color: #fff}
.html-chat-js-button-holder{ margin-bottom: 0px;margin-top: 10px; }
.html-chat-js-button-holder input{ width: 220px; }
.html-chat-js-answer{ float:right; }
.html-chat-js-answer a{ color: #777;font-size: 12px; font-family: cursive;}
.html-chat-js-answer a:hover{ color: #338;font-size: 12px; font-family: cursive;}
.html-chat-msg{ margin: 0px; }
</style>
 
<script>
 
   /**
    * Чат работает на comet-server.ru
    * По любым вопросам обращайтесь support@comet-server.ru или на сайт comet-server.ru
    */
    $(document).ready(function()
    {
       // Запуск api комет сервера
       CometServer().start({dev_id: 1116 }) // Идентификатор разработчика на comet-server.ru
 
       // Запуск чата. Передаём ему элемент в котором надо создать окно чата.
       htmljs_Chat_Init( $("#html-chat") )
    });
</script>


{% endfor %}
{% endblock %}

project/templates/enter.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block additional_js %}
    <script src="{% static "js/timeline.js" %}"></script>
{% endblock %}

{% block main %}
    <!-- enter FORM START HERE -->
      <div class="container">

      {% if form.errors %}
        <p>Пожалуйста введите корректную почту и пароль</p>
      {% endif %}
      <form class="form-signin" action="" role="form" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Вхoд</h2>
        <label for="username" class="sr-only">Почта</label>
        <input type="email" id="id_username" class="form-control" name="username" placeholder="Почта" required autofocus>
        <label for="password" class="sr-only">Пароль</label>
        <input type="password" id="id_password" class="form-control" name="password" placeholder="Пароль" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Запомнить меня
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
{#        <input type="hidden" name="next" value="{{ next }}" />#}
      </form>
      <p style="text-align: center;">У вас нету аккаунта ? <a href="{% url 'register' %}">Создайте его</a></p>
    </div> <!-- /container -->
    </br>
    </br>
    </br>

<!-- ENTER FORM END HERE-->
{% endblock %}

project/templates/event.html
{% extends "main.html" %}
{% load staticfiles %}

{% block main %}

      <li class="dropdown">
        <a href="chat.html" class="dropdown-toggle" data-toggle="dropdown">Чат <i class="fa fa-angle-down"></i></a>
        <ul class="dropdown-menu">
          <li><a href="chat.html">Общий чат</a></li>
          <li><a href="#">Чат факультета</a></li>
        </ul>
    </li>
      <li><a href="enter.html">Вход</a></li>
    </ul>
   </div>
  </div> 
</nav>    
<!--HERE START EVENT PART-->
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<!--HERE EVENT PART ENDED-->
{% endblock %}

project/templates/faq.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block main %}
<!--HERE START FAQ PART-->
</br>
</br>


<div class="container ">
    <div class="panel-group" id="faqAccordion">

        {% for object in object_list %}
        <div class="panel panel-default ">
            <div class="panel-heading accordion-toggle question-toggle collapsed" data-toggle="collapse" data-parent="#faqAccordion" data-target="#question{{ object.id }}">
                 <h4 class="panel-title">
                    <a href="#" class="ing">Q: {{ object.question }}</a>
              </h4>

            </div>
            <div id="question{{ object.id }}" class="panel-collapse collapse" style="height: 0px;">
                <div class="panel-body">
                     <h5><span class="label label-primary">Ответ</span></h5>

                    <p>{{ object.answer }}</p>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
    <!--/panel-group-->
</div>

</br>
</br>
</br>
</br>
</br>
<!--HERE ENDED FAQ PART-->
{% endblock %}

project/templates/history.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block main %}
<!--HERE START HISTORY PART -->


<!--HERE HISTORY PART ENDED-->
<!--ARTICLE PART START HERE-->
{% for article in object_list %}
<article class="article__item container">
  <div class="row">
    <header class="article__item__header col-xs-12">
      <h2>
        <a href="#">{{ article.title }}</a>
      </h2>
      <p class="article__item__meta">
        <time datetime="2016-07-12T22:37:25+00:00">{{ article.pub_date|date:'j.m.Y' }}</time> ·
        <a href="#"><i class="fa fa-comments"></i> <span class="dsq-postid" data-dsqidentifier="#">0</span></a>
      </p>
    </header>
      {% if article.image %}
      <div class="article__item__img col-xs-12 ">
          <a href="#"><img width="1170" height="360" class="img-responsive"
                           src="{{ article.image.url }}" alt="img"></a>
      </div>
      {% endif %}
        <div class="article__item__desc col-xs-12">
      <p>{{ article.text|slice:':850' }}
        {% if article.text.length > 850 %}...{% endif %}
      </p>
    </div>
    <footer class="article__item__read-more col-xs-12">
      <a href="#">
        Читать дальше        <i class="fa fa-arrow-right"></i>
      </a>
    </footer>
  </div>
  <hr>
</article>
{% endfor %}
<!--ARTICLE PART ENDED HERE-->
{% endblock %}

project/templates/index.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block main %}
<div class="jumbotron">
   <div class="container">
     <div class="row">
     <!--<img class="img-responsive" src="images/main-photo.jpg">-->

    </div>
  </div>
</div>

{% for article in object_list %}
    <article class="article__item container">
      <div class="row">
        <header class="article__item__header col-xs-12">
          <h2>
            <a href="#">{{ article.title }}</a>
          </h2>
          <p class="article__item__meta">
            <time datetime="2016-07-12T22:37:25+00:00">{{ article.pub_date|date:'j.m.Y' }}</time>
            <a href="#"><i class="fa fa-comments"></i> <span class="dsq-postid" data-dsqidentifier="#">0</span></a>
          </p>
        </header>
          {% if article.image %}
          <div class="article__item__img col-xs-12 ">
              <a href="#"><img width="1170" height="360" class="img-responsive"
                               src="{{ article.image.url }}" alt="img"></a>
          </div>
          {% endif %}
            <div class="article__item__desc col-xs-12">
          <p>{{ article.text|slice:':850' }}
            {% if article.text.length > 850 %}...{% endif %}
          </p>
        </div>
        <footer class="article__item__read-more col-xs-12">
          <a href="#">
            Читать дальше        <i class="fa fa-arrow-right"></i>
          </a>
        </footer>
      </div>
      <hr>
    </article>
{% endfor %}
{% endblock %}

project/templates/main.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="homepage">

<nav class="navbar navbar-default" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand img-responsible img-circle" href="{% url 'mainpage' %}"><img src="{% static "images/logo-kz.png" %}" alt="logo"></a>
    </div>
<div class="collapse navbar-collapse navbar-right">
    <ul class="nav navbar-nav">
        <li><a href="{% url 'mainpage' %}">Главная</a></li>
        <li><a href="event.html">События</a></li>
        <li><a href="{% url 'history' %}">История</a></li>
        <li><a href="{% url 'faq' %}">FAQ</a></li>
        <li><a href="charity.html">Благотворительность</a></li>
        <li><a href="partners.html">Партнеры</a></li>

      <li class="dropdown">
        <a href="chat.html" class="dropdown-toggle" data-toggle="dropdown">Чат <i class="fa fa-angle-down"></i></a>
        <ul class="dropdown-menu">
          <li><a href="chat.html">Общий чат</a></li>
          <li><a href="#">Чат факультета</a></li>
        </ul>
    </li>
      <li>
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Выход</a>
          {% else %}
              <a href="{% url 'login' %}?next={{ request.path }}">Вход</a>
          {% endif %}
      </li>
    </ul>
   </div>
  </div>
</nav>

{% block main %}
{% endblock %}

<footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2016 <a target="_blank" href="http://vk.com/ivanulo" title="Kazakhstan student society">Our web-stud</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                    <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                        <li><a href="#">Главная</a></li>
                        <li><a href="{% url 'history' %}">Наша история</a></li>
                        <li><a href="{% url 'faq' %}">Faq</a></li>
                        <li><a href="#">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

  </div>
{% endblock %}

project/templates/partners.html
{% extends "main.html" %}
{% load staticfiles %}


{% block main %} <!--PARTNERS PART-->
<div class="container">
  <div class="row">
    <div class="col-lg-9">
        <h2>Название партн</h2>  
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
      <div class="col-lg-3 partners-contacts">
        <p>Twitter, Inc.</br>
          795 Folsom Ave, Suite 600</br>
          San Francisco, CA 94107</br>
          P: (123) 456-7890</br>
          Full Name</br>
          first.last@example.co</br>
        </p>
  </div>
  </div>
</div>
</br>
</br>
</br>
</br>
</br>
</br>

{% endblock %}

project/templates/registration.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block main %}
<!--REGISTRAION FROM-->
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">Ай-да к нам!</div>
                <div class="panel-body">
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                    <form role="form" method="post" action="" accept-charset="UTF-8">
                        {% csrf_token %}

                        {{ form.first_name.errors }}
                        <label for="first_name">Ваше имя</label>
                        <input type="text" id="id_first_name" class="form-control" name="first_name" placeholder="Василий">

                        {{ form.last_name.errors }}
                        <label for="last_name">Ваша фамилия</label>
                        <input type="text" id="id_last_name" class="form-control" name="last_name" placeholder="Пупкин">

                        {{ form.date_of_birth.errors }}
                         <label for="date_of_birth">Дата рождения</label>
                        <input type="text" id="id_date_of_birth" class="form-control" name="date_of_birth" placeholder="дд/мм/гг">

                        {{ form.email.errors }}
                          <label for="email" class="m-t-10">Email Address</label>
                        <input type="text" id="id_email" class="form-control" name="email" placeholder="Example: john.smith@gmail.com">

                        {{ form.gender.errors }}
                        <label for="gender" class="m-t-10">Uni</label>
{#                        <select id="id_gender" class="form-control" name="gender">#}
{#                            <option value="unknown">Невыбрано</option>#}
{#                            <option value="alabama">Первый</option>#}
{#                            <option value="alaska">Второй</option>#}
{#                        </select>#}
                        {{ form.gender }}

                        {{ form.faculty.errors }}
                        <label for="faculty" class="m-t-10">Выбери свой факультет</label>
{#                        <select id="id_faculty" class="form-control" name="faculty">#}
{#                            <option value="unknown">Нету</option>#}
{#                            <option value="physic">Физ-мат</option>#}
{#                            <option value="phylosophy">Фил-фак</option>#}
{#                        </select>#}
                        {{ form.faculty }}

                        {{ form.phone_number.errors }}
                        <label for="phone_number">Номер мобильного</label>
                        <input type="numbers" id="id_phone_number" class="form-control" name="phone_number" placeholder="+38x-xx-xx-xxx">

                        {{ form.city.errors }}
                        <label for="city" class="m-t-10">Выберите свой город</label>
{#                        <select id="id_city" class="form-control" name="city">#}
{#                            <option value="unknown">Первый</option>#}
{#                            <option value="physic">Астана</option>#}
{#                            <option value="phylosophy">Другой</option>#}
{#                        </select>#}
                        {{ form.city }}

                        {{ form.address.errors }}
                        <label for="address">Ваш адрес</label>
                        <input type="text" id="id_address" class="form-control" name="address" placeholder="Страна/Город/Улица">

                        {{ form.password1.errors }}
                        <label for="password1" class="m-t-10">Пароль</label>
                        <input type="password" id="id_password1" class="form-control" name="password1" placeholder="">

                        {{ form.password2.errors }}
                        <label for="password2" class="m-t-10">Повторите пароль</label>
                        <input type="password2" id="id_password2" class="form-control" name="password2" placeholder="">
                        
                        <center><input type="submit" class="btn btn-primary m-t-10" id="submitbtn" name="submit" value="Создать аккаунт"></center>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!--<REG FORM ENDED HERE -->
{% endblock %}